# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Alex Rios
tagline:          Portfolio
description:      'B.S. Electrical Engineering and Computer Science. Virtual Reality & Unity3d Developer. <a href="https://www.linkedin.com/in/alexander-angulo-rios-6a529a225/" target="_blank">LinkedIn</a>'
url:              http://alexarios.github.io
baseurl:          /

author:
  name:           'Alex Rios'
  url:            https://alexarios.github.io

paginate:         100
paginate_path:    "blog/index.html" 

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alexarios/alexarios.github.io

# Gems
plugins: [jekyll-paginate, jekyll-feed, jekyll-sass-converter, jekyll-seo-tag, jekyll-sitemap, jekyll-watch]