# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alex Rios
tagline:          'https://www.linkedin.com/in/alexander-angulo-rios-6a529a225/'
description:      ''
url:              https://alexarios.github.io
baseurl:          /

author:
  name:           'Alex Rios'
  url:            https://alexarios.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alexarios/alexarios.github.io
