# Site settings
title: Portfolio
description: Alex Rios, AR/VR Designer and Software Engineer
# baseurl: /
url: https://alexarios.github.io

# User settings
username: Alex Rios
user_description: I'm a recent graduate from UC Berkeley, where I received my Bachelors degree for Electrical Engineering and Computer Science. I enjoy video games, music, & any and everything Augmented/Virtual Reality related.
user_title: AR/VR Designer and Software Engineer
email: anguloriosalexander@gmail.com
# twitter_username: lorem_ipsum
github_username:  alexarios
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
