# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alex Rios
tagline:          'B.S. Electrical Engineering and Computer Science @ UC Berkeley. Virtual Reality & Unity3d Development.'
description:      '<a href="https://www.linkedin.com/in/alexander-angulo-rios-6a529a225/" target="_blank">LinkedIn</a>'
url:              http://alexarios.github.io
baseurl:          /

author:
  name:           'Alex Rios'
  url:            https://alexarios.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alexarios/alexarios.github.io